/**
 * The sqlite→Postgres translation is the part of the ledger port that can be
 * silently wrong: it turns a dialect the tests exercise (sqlite) into one they
 * cannot (no live Postgres in CI). So the translation itself is unit-tested here,
 * against the exact SQL shapes store.ts emits. A live-Postgres round-trip is still
 * required before any funding deploy (docs/hosted-platform-plan.md) — these tests
 * prove the rewrite, not the wire.
 */
import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { toPgPlaceholders, translateQuery, translateSchema } from "./db";

describe("toPgPlaceholders", () => {
  it("numbers positional placeholders left to right", () => {
    assert.equal(toPgPlaceholders("VALUES (?, ?, ?)"), "VALUES ($1, $2, $3)");
  });
  it("leaves a ? inside a single-quoted string alone", () => {
    // Not in today's store SQL, but the guarantee must hold or a literal breaks.
    assert.equal(toPgPlaceholders("SET note = 'why?' WHERE id = ?"), "SET note = 'why?' WHERE id = $1");
  });
  it("does nothing to SQL with no placeholders", () => {
    assert.equal(toPgPlaceholders("SELECT 1"), "SELECT 1");
  });
});

describe("translateQuery", () => {
  it("turns INSERT OR IGNORE into an ON CONFLICT DO NOTHING", () => {
    assert.equal(
      translateQuery("INSERT OR IGNORE INTO discovered_pools (address, symbol) VALUES (?, ?)"),
      "INSERT INTO discovered_pools (address, symbol) VALUES ($1, $2) ON CONFLICT DO NOTHING",
    );
  });
  it("rewrites unixepoch() in a VALUES list and still numbers the placeholders", () => {
    assert.equal(
      translateQuery("INSERT INTO flows (agent_id, amount_usdg, at) VALUES (?, ?, unixepoch())"),
      "INSERT INTO flows (agent_id, amount_usdg, at) VALUES ($1, $2, EXTRACT(EPOCH FROM now())::bigint)",
    );
  });
  it("rewrites unixepoch() arithmetic in a WHERE window", () => {
    assert.equal(
      translateQuery("SELECT 1 WHERE created_at > unixepoch() - 86400 AND agent_id = ?"),
      "SELECT 1 WHERE created_at > EXTRACT(EPOCH FROM now())::bigint - 86400 AND agent_id = $1",
    );
  });
  it("normalises ON CONFLICT(cols) to a spaced list and preserves an explicit DO NOTHING", () => {
    // The trench_positions seed: already has its own conflict target, so nothing is appended.
    assert.equal(
      translateQuery(
        "INSERT INTO trench_positions (agent_id, mode, symbol, entry_liquidity_usd) VALUES (?, ?, ?, ?) ON CONFLICT(agent_id, mode, symbol) DO NOTHING",
      ),
      "INSERT INTO trench_positions (agent_id, mode, symbol, entry_liquidity_usd) VALUES ($1, $2, $3, $4) ON CONFLICT (agent_id, mode, symbol) DO NOTHING",
    );
  });
  it("carries a real upsert through: spaced conflict target, excluded refs intact, 1..n placeholders", () => {
    const out = translateQuery(
      `INSERT INTO positions (agent_id, symbol, price_usd, updated_at)
       VALUES (?, ?, ?, unixepoch())
       ON CONFLICT(agent_id, symbol) DO UPDATE SET
         price_usd = excluded.price_usd, updated_at = excluded.updated_at`,
    );
    assert.match(out, /VALUES \(\$1, \$2, \$3, EXTRACT\(EPOCH FROM now\(\)\)::bigint\)/);
    assert.match(out, /ON CONFLICT \(agent_id, symbol\) DO UPDATE/);
    assert.match(out, /price_usd = excluded\.price_usd/); // Postgres reads `excluded` case-insensitively
    assert.doesNotMatch(out, /\?/);
  });
});

describe("translateSchema", () => {
  it("converts an autoincrement PK to a Postgres identity column", () => {
    assert.equal(
      translateSchema("id INTEGER PRIMARY KEY AUTOINCREMENT,"),
      "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
    );
    assert.doesNotMatch(translateSchema("id INTEGER PRIMARY KEY AUTOINCREMENT"), /AUTOINCREMENT/);
  });
  it("maps sqlite's 64-bit INTEGER to BIGINT and REAL to DOUBLE PRECISION", () => {
    assert.equal(translateSchema("chain_id INTEGER NOT NULL"), "chain_id BIGINT NOT NULL");
    assert.equal(translateSchema("amount_usdg REAL NOT NULL"), "amount_usdg DOUBLE PRECISION NOT NULL");
  });
  it("rewrites a unixepoch default", () => {
    assert.equal(
      translateSchema("created_at INTEGER NOT NULL DEFAULT (unixepoch())"),
      "created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::bigint)",
    );
  });
  it("strips PRAGMA and makes ADD COLUMN idempotent", () => {
    assert.equal(translateSchema("PRAGMA journal_mode = WAL;").trim(), "");
    assert.equal(
      translateSchema("ALTER TABLE trades ADD COLUMN gas_wei TEXT"),
      "ALTER TABLE trades ADD COLUMN IF NOT EXISTS gas_wei TEXT",
    );
  });
  it("never mistakes lowercase prose in a comment for a type keyword", () => {
    // The real schema's comments say things like "the real thing" and "an integer".
    const s = translateSchema("-- realized P&L here is the real thing, an integer really\n  x REAL");
    assert.match(s, /the real thing, an integer really/); // comment untouched
    assert.match(s, /x DOUBLE PRECISION/); // the actual type still converted
  });
});
